### ISSUE TITLE
Installation process in ubuntu

### ISSUE THREAD

**Issue by johnfelipe** [taurenk/Angular-Map-Demo#2]
61  git clone https://github.com/taurenk/Angular-Map-Demo.git
	   62  cd Angular-Map-Demo/
	   63  npm install
	   64  gulp dev
	   65  sudo npm install -g gulp
	   66  gulp dev
	   67  gulp prod
	   68  gulp dev
	   69  sudo apt-add-repository ppa:izx/askubuntu
	   70  sudo apt-get install libnotify-bin
	   71  gulp dev

after gulp dev what i have to do?

**Comment by taurenk** [comment]
Hi John,

Switch in the the directory named "build" and then run the following command "http-server". After you run that, you should be able to to access the demo site in your browser!

Let me know if that works for you.
